project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('newsportal.urls')),

]

newsportal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import F, Sum, Max, Min, Avg, Count
from django.urls import reverse

article = 'a'
news = 'n'
POSTS = (
    (article, 'Статья'),
    (news, 'Новость')
)


 

    

class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        if postRat.get('postRating'):
            pRat += postRat.get('postRating')
        commentRat = self.author.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        if commentRat.get('commentRating'):
            cRat += commentRat.get('commentRating')
        self.rating = pRat*3 + cRat
        self.save()

    def __str__(self):
        return self.author.username

class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    type_post = models.CharField(max_length=1, choices=POSTS, verbose_name='Тип поста')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    category = models.ManyToManyField(Category, through="PostCategory", verbose_name='Категория')
    title =  models.CharField(max_length=255, verbose_name='Оглавление')
    content = models.TextField( verbose_name='Содержание')
    rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг')

    def get_absolute_url(self):
        return reverse('one_news', args=[str(self.id)])

    def __str__(self):
        return f'{self.get_type_post_display()} - {self.title}'

    def like(self):
        self.rating += 1  
      
    def dislike(self):
        self.rating -= 1
        self.save()
      
    def  preview(self):
        p = self.content[:124]
        return f'{p}...'

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
         return f'{str(self.post)} , {str(self.category)}'



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'Комментаий к посту {self.post} от пользователя {self.user}'


    def like(self):
        self.rating += 1
        self.save()
    def dislike(self):
        self.rating -= 1
        self.save()

templates/article_delete.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}Удаление статьи{% endblock title %}
{% block content %}

  {% if perms.newsportal.delete_post  %}

<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>

{% endfor %}


{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="">Главная саница<div class="logo"></div></a></li>


			<li><a href="">Создать новость</a></li>
        <li><a href="">Создать статью</a></li>

			<li class="last"><a href="">Войти</a></li>
        <li class="last"><a href="">Выйти</a></li>

			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
  
	<ul id="leftchapters">
   
    <li class="selected"><a href="">Все посты (только просмотр)</a></li>
   
    <li><a href="">Новости</a></li>
  
    
    <li><a href="">Статьи</a></li>
  
		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>
		</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

templates/comments.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
{% if comments %}
<h1>Комментарии</h1>
{% for comment in comments %}
Комментарий от пользователя {{ comment.user }} к посту
<a href="{% url 'showpost' comment.post.pk %}">{{ comment.post }}</a><br>
<a href="{% url 'showcomment' comment.pk %}">{{ comment.content|censor }}</a><br>
рейтинг {{ comment.rating }}<br>
<hr>
{% endfor %}
{% else %}
<h1>Комментариев нет</h1>
{% endif %}
{% endblock content %}

templates/default.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'index' %}">Главная саница<div class="logo"></div></a></li>

         {% if perms.newsportal.add_post  %}
 
			<li><a href="{% url 'news_create' %}">Создать новость</a></li>
        <li><a href="{% url 'article_create' %}">Создать статью</a></li>
   {% endif %}

        
{% if not request.user.is_authenticated %}
        	
			<li class="last"><a href="/accounts/login/">Войти</a></li>
        <li class="last"><a href="/accounts/signup/">Зарегистроваться</a></li>
        <li class="last"> Вы не авторизованы</li>

         {% else %}
	<li class="last">{{ user.username }}</li>
        
        <li class="last"><a href="/accounts/logout/">Выйти</a></li>
        {% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
  
	<ul id="leftchapters">
   

   
    <li><a href="{% url 'news' %}">Новости</a></li>
  
    
    <li><a href="{% url 'articles' %}">Статьи</a></li>
  

	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

templates/index.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}Все посты{% endblock title %}

{% block content %}
<h1 align="center">{{ title }}</h1>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>



{% if posts %}
{% include 'includes/paginations.html' %}


<hr>
{% for n in posts %}
<h2>{{ n.get_type_post_display }}</h2>
<h6>
{% for cat in n.category.all %}
{{ cat }}    {% if not forloop.last %}, {% endif %}
{% endfor %}
</h6>

<h4>{{ n.time_created|date:'Y-m-d' }} | Рейтинг: {{ n.rating }}
    | Автор: {{ n.author }} | Комментариев: {{ n.comment_set.count }} </h4>

<h2>{{ n.title|censor }}</h2>
<p>{{ n.content|truncatechars:200|censor}}</p>
   <p class="link-read-post"><a href="{{ n.get_absolute_url }}">Читать пост</a>
<hr>
{% endfor %}

{% include 'includes/paginations.html' %}
{% else %}
<h1>Постов нет</h1>

{% endif %}

<br><br>{% endblock content %}

templates/index_articles.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}Статьи{% endblock title %}

{% block content %}
<h1 align="center">{{ title }}</h1>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>

{% if articles %}
{% include 'includes/paginations.html' %}

<hr>
{% for a in articles %}

<h6>
{% for cat in a.category.all %}
{{ cat }}    {% if not forloop.last %}, {% endif %}
{% endfor %}
</h6>

<h4>{{ a.time_created|date:'Y-m-d' }} | Рейтинг: {{ a.rating }}
    | Автор: {{ a.author }} | Комментариев: {{ a.comment_set.count }} </h4>

<h2>{{ a.title|censor }}</h2>
<p>{{ a.content|truncatechars:200|censor}}</p>
   <p class="link-read-post"><a href="{% url 'one_article' a.pk %}">Читать пост</a>
<hr>
{% endfor %}

{% include 'includes/paginations.html' %}
{% else %}
<h1>Статей нет</h1>

{% endif %}

<br><br>{% endblock content %}

templates/index_news.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}Новости{% endblock title %}

{% block content %}
<h1 align="center">{{ title }}</h1>


   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>

{% if news %}
{% include 'includes/paginations.html' %}


<hr>
{% for n in news %}

<h6>
{% for cat in n.category.all %}
{{ cat }}    {% if not forloop.last %}, {% endif %}
{% endfor %}
</h6>

<h4>{{ n.time_created|date:'Y-m-d' }} | Рейтинг: {{ n.rating }}
    | Автор: {{ n.author }} | Комментариев: {{ n.comment_set.count }} </h4>

<h2>{{ n.title|censor }}</h2>
<p>{{ n.content|truncatechars:200|censor}}</p>
   <p class="link-read-post"><a href="{% url 'one_news' n.pk %}">Читать пост</a>
<hr>
{% endfor %}

{% include 'includes/paginations.html' %}
{% else %}
<h1>Новостей нет</h1>

{% endif %}

<br><br>{% endblock content %}

templates/news.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}Новости{% endblock title %}

{% block content %}



{% if news %}
{% include 'includes/paginations.html' %}

<h1>Новости</h1>  
<hr>
{% for n in news %}

<h6>
{% for cat in n.category.all %}
{{ cat }}    {% if not forloop.last %}, {% endif %}
{% endfor %}
</h6>

<h4>{{ n.time_created|date:'Y-m-d' }} | Рейтинг: {{ n.rating }}
    | Автор: {{ n.author }} | Комментариев: {{ n.comment_set.count }} </h4>

<h2>{{ n.title|censor }}</h2>
<p>{{ n.content|truncatechars:200|censor}}</p>
   <p class="link-read-post"><a href="{% url 'one_news' n.pk %}">Читать пост</a>
<hr>
{% endfor %}

{% include 'includes/paginations.html' %}
{% else %}
<h1>Новостей нет</h1>

{% endif %}

<br><br>{% endblock content %}

templates/news_delete.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}Удаление новости{% endblock title %}
{% block content %}
  {% if perms.newsportal.delete_post  %}

<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endif %}
{% endblock content %}

templates/one_article.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h4>{{ article.time_created|date:'d:m:Y' }}</h4>
<p>Рейтинг {{ article.rating }}</p>
<h1>Автор: {{ article.author }}</h1>
<h1>{{ article.title }}</h1>
<p>{{ article.content|censor }}</p>


       {% if perms.newsportal.add_post  %}


<p><a href="{% url 'article_edit' article.pk %}">Изменить</a>
   {% endif %}

   {% if perms.newsportal.delete_post  %}
    <a href="{% url 'article_delete' article.pk %}">Удалить</a></p></p>
{% endif %}

{% if  article.comment_set.all %}
<br>
Комментарии: {% for comment in article.comment_set.all %}
{{ comment.user }} <br> <a href="{% url 'showcomment' comment.pk %}">{{ comment.content|censor }}</a>
<br> рейтинг  {{ comment.rating }}<hr>
{% endfor %}

{% else %}<br> Комментариев нет
{% endif %}
<a href="{% url 'like-news' article.pk %}">like</a>
<a href="{% url 'dislike-news' article.pk %}">dislike</a>
{% endblock content %}

templates/one_news.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %}{{ title }}{% endblock title %}

{% block content %} <br>
<h4>{{ news.time_created|date:'d:m:Y' }}</h4>
{% if news.category.all %}
 {% for cat in news.category.all %}
{{ cat }}    {% if not forloop.last %}, {% endif %}
{% endfor %}

{% endif %}
<h2>{{ news.get_type_post_display }}</h2>
<h1>Автор: {{ news.author }}</h1>
<h1>{{ news.title|censor }}</h1>
<p>{{ news.content|censor }}</p>

    {% if perms.newsportal.add_post  %}

<p><a href="{% url 'news_edit' news.pk %}">Изменить</a>

  {% endif %}

   {% if perms.newsportal.delete_post  %}
    <a href="{% url 'news_delete' news.pk %}">Удалить</a></p>
{% endif %}

<h5>Рейтинг: {{ news.rating }}</h5>





{% if  news.comment_set.all %}
<br>
Комментарии: {% for comment in news.comment_set.all %}
{{ comment.user }} <br> <a href="{% url 'showcomment' comment.pk %}">{{ comment.content|censor }}</a>
<br> рейтинг  {{ comment.rating }}<hr>
{% endfor %}

{% else %}<br> Комментариев нет
{% endif %}


<a href="{% url 'like-news' news.pk %}">like</a>
<a href="{% url 'dislike-news' news.pk %}">dislike</a>

{% endblock content %}

templates/post_edit.html
{% extends 'default.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    {% if perms.newsportal.add_post  %}
<h1>{{ title }}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value={{ button }} />
</form> <br>
{% endif %}
{% endblock content %}

templates/showcomment.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
<p>{{ comment.content|censor }}</p>
<p>Rating {{ comment.rating }}</p>
<a href="{% url 'like-comment' comment.pk %}">like</a>
<a href="{% url 'dislike-comment' comment.pk %}">dislike</a>

{% endblock content %}

templates/showpost.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h1>{{ post.title|censor }}</h1>
<p>{{ post.content|censor }}</p>
<p>Рейтинг {{ post.rating }}</p>


{% endblock content %}